name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    description: 'Environment to run tests against'
    type: environment
    required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Environment
      run: env

    - name: Debug
      env:
        USER: "${{ github.ref_type == 'tag' && 'TAG' || github.actor }}"

      run: make debug
