name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  LIBVERSION: "${{ github.ref_type == 'tag' && 'TAG' || github.actor }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Environment
      run: env

    - name: Debug
      run: make debug
