name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    description: 'Environment to run tests against'
    type: environment
    required: true

env:
  USER: "${{ github.ref_type == 'tag' && github.ref_name || github.actor }}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Environment
      run: env

    - name: Debug
      run: make debug
